name: 🛡️ Daily GitHub Grade Tracker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clone your repo
        uses: actions/checkout@v3

      - name: 📊 Generate badge + score
        run: |
          curl -s https://api.github.com/users/nholuongut | jq '.public_repos, .followers, .following'
          
          mkdir -p .github/assets

          echo "![GitHub Grade](https://img.shields.io/badge/GitHub%20Grade-A%2B-brightgreen?style=for-the-badge)" > .github/assets/badge.md

      - name: 🔁 Commit badge
        run: |
          git config --global user.name "nholuongut"
          git config --global user.email "luongutnho.dxc@gmail.com"
          git add .github/assets/badge.md
          git commit -m "🚀 Auto-update badge.md"
          git push
